/* eslint-disable */

// @ts-nocheck

// noinspection JSUnusedGlobalSymbols

// This file was automatically generated by TanStack Router.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import { Route as rootRouteImport } from './routes/__root'
import { Route as IndexRouteImport } from './routes/index'
import { Route as AuthenticatedRouteRouteImport } from './routes/_authenticated/route'
import { Route as ForgotPasswordRouteImport } from './routes/forgot-password'
import { Route as LoginRouteImport } from './routes/login'
import { Route as ResetPasswordRouteImport } from './routes/reset-password'
import { Route as SignupRouteImport } from './routes/signup'
import { Route as AuthCallbackRouteImport } from './routes/auth.callback'
import { Route as AuthenticatedAppIndexRouteImport } from './routes/_authenticated/app.index'
import { Route as AuthenticatedAppKitchenRouteImport } from './routes/_authenticated/app.kitchen'
import { Route as AuthenticatedAppPlannerRouteImport } from './routes/_authenticated/app.planner'
import { Route as AuthenticatedAppSettingsRouteImport } from './routes/_authenticated/app.settings'
import { Route as AuthenticatedAppCollectionsIndexRouteImport } from './routes/_authenticated/app.collections.index'
import { Route as AuthenticatedAppCollectionsCollectionIdRouteImport } from './routes/_authenticated/app.collections.$collectionId'
import { Route as AuthenticatedAppRecipesIndexRouteImport } from './routes/_authenticated/app.recipes.index'
import { Route as AuthenticatedAppRecipesImportRouteImport } from './routes/_authenticated/app.recipes.import'
import { Route as AuthenticatedAppRecipesNewRouteImport } from './routes/_authenticated/app.recipes.new'
import { Route as AuthenticatedAppShoppingIndexRouteImport } from './routes/_authenticated/app.shopping.index'
import { Route as AuthenticatedAppShoppingShoppingListIdRouteImport } from './routes/_authenticated/app.shopping.$shoppingListId'
import { Route as AuthenticatedAppRecipesRecipeIdIndexRouteImport } from './routes/_authenticated/app.recipes.$recipeId.index'
import { Route as AuthenticatedAppRecipesRecipeIdEditRouteImport } from './routes/_authenticated/app.recipes.$recipeId.edit'

const IndexRoute = IndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => rootRouteImport,
} as any)
const AuthenticatedRouteRoute = AuthenticatedRouteRouteImport.update({
  id: '/_authenticated',
  getParentRoute: () => rootRouteImport,
} as any)
const ForgotPasswordRoute = ForgotPasswordRouteImport.update({
  id: '/forgot-password',
  path: '/forgot-password',
  getParentRoute: () => rootRouteImport,
} as any)
const LoginRoute = LoginRouteImport.update({
  id: '/login',
  path: '/login',
  getParentRoute: () => rootRouteImport,
} as any)
const ResetPasswordRoute = ResetPasswordRouteImport.update({
  id: '/reset-password',
  path: '/reset-password',
  getParentRoute: () => rootRouteImport,
} as any)
const SignupRoute = SignupRouteImport.update({
  id: '/signup',
  path: '/signup',
  getParentRoute: () => rootRouteImport,
} as any)
const AuthCallbackRoute = AuthCallbackRouteImport.update({
  id: '/auth/callback',
  path: '/auth/callback',
  getParentRoute: () => rootRouteImport,
} as any)
const AuthenticatedAppIndexRoute = AuthenticatedAppIndexRouteImport.update({
  id: '/app/',
  path: '/app/',
  getParentRoute: () => AuthenticatedRouteRoute,
} as any)
const AuthenticatedAppKitchenRoute = AuthenticatedAppKitchenRouteImport.update({
  id: '/app/kitchen',
  path: '/app/kitchen',
  getParentRoute: () => AuthenticatedRouteRoute,
} as any)
const AuthenticatedAppPlannerRoute = AuthenticatedAppPlannerRouteImport.update({
  id: '/app/planner',
  path: '/app/planner',
  getParentRoute: () => AuthenticatedRouteRoute,
} as any)
const AuthenticatedAppSettingsRoute =
  AuthenticatedAppSettingsRouteImport.update({
    id: '/app/settings',
    path: '/app/settings',
    getParentRoute: () => AuthenticatedRouteRoute,
  } as any)
const AuthenticatedAppCollectionsIndexRoute =
  AuthenticatedAppCollectionsIndexRouteImport.update({
    id: '/app/collections/',
    path: '/app/collections/',
    getParentRoute: () => AuthenticatedRouteRoute,
  } as any)
const AuthenticatedAppCollectionsCollectionIdRoute =
  AuthenticatedAppCollectionsCollectionIdRouteImport.update({
    id: '/app/collections/$collectionId',
    path: '/app/collections/$collectionId',
    getParentRoute: () => AuthenticatedRouteRoute,
  } as any)
const AuthenticatedAppRecipesIndexRoute =
  AuthenticatedAppRecipesIndexRouteImport.update({
    id: '/app/recipes/',
    path: '/app/recipes/',
    getParentRoute: () => AuthenticatedRouteRoute,
  } as any)
const AuthenticatedAppRecipesImportRoute =
  AuthenticatedAppRecipesImportRouteImport.update({
    id: '/app/recipes/import',
    path: '/app/recipes/import',
    getParentRoute: () => AuthenticatedRouteRoute,
  } as any)
const AuthenticatedAppRecipesNewRoute =
  AuthenticatedAppRecipesNewRouteImport.update({
    id: '/app/recipes/new',
    path: '/app/recipes/new',
    getParentRoute: () => AuthenticatedRouteRoute,
  } as any)
const AuthenticatedAppShoppingIndexRoute =
  AuthenticatedAppShoppingIndexRouteImport.update({
    id: '/app/shopping/',
    path: '/app/shopping/',
    getParentRoute: () => AuthenticatedRouteRoute,
  } as any)
const AuthenticatedAppShoppingShoppingListIdRoute =
  AuthenticatedAppShoppingShoppingListIdRouteImport.update({
    id: '/app/shopping/$shoppingListId',
    path: '/app/shopping/$shoppingListId',
    getParentRoute: () => AuthenticatedRouteRoute,
  } as any)
const AuthenticatedAppRecipesRecipeIdIndexRoute =
  AuthenticatedAppRecipesRecipeIdIndexRouteImport.update({
    id: '/app/recipes/$recipeId/',
    path: '/app/recipes/$recipeId/',
    getParentRoute: () => AuthenticatedRouteRoute,
  } as any)
const AuthenticatedAppRecipesRecipeIdEditRoute =
  AuthenticatedAppRecipesRecipeIdEditRouteImport.update({
    id: '/app/recipes/$recipeId/edit',
    path: '/app/recipes/$recipeId/edit',
    getParentRoute: () => AuthenticatedRouteRoute,
  } as any)

export interface FileRoutesByFullPath {
  '/': typeof IndexRoute
  '/forgot-password': typeof ForgotPasswordRoute
  '/login': typeof LoginRoute
  '/reset-password': typeof ResetPasswordRoute
  '/signup': typeof SignupRoute
  '/auth/callback': typeof AuthCallbackRoute
  '/app/kitchen': typeof AuthenticatedAppKitchenRoute
  '/app/planner': typeof AuthenticatedAppPlannerRoute
  '/app/settings': typeof AuthenticatedAppSettingsRoute
  '/app/': typeof AuthenticatedAppIndexRoute
  '/app/collections/$collectionId': typeof AuthenticatedAppCollectionsCollectionIdRoute
  '/app/recipes/import': typeof AuthenticatedAppRecipesImportRoute
  '/app/recipes/new': typeof AuthenticatedAppRecipesNewRoute
  '/app/shopping/$shoppingListId': typeof AuthenticatedAppShoppingShoppingListIdRoute
  '/app/collections/': typeof AuthenticatedAppCollectionsIndexRoute
  '/app/recipes/': typeof AuthenticatedAppRecipesIndexRoute
  '/app/shopping/': typeof AuthenticatedAppShoppingIndexRoute
  '/app/recipes/$recipeId/edit': typeof AuthenticatedAppRecipesRecipeIdEditRoute
  '/app/recipes/$recipeId/': typeof AuthenticatedAppRecipesRecipeIdIndexRoute
}
export interface FileRoutesByTo {
  '/': typeof IndexRoute
  '/forgot-password': typeof ForgotPasswordRoute
  '/login': typeof LoginRoute
  '/reset-password': typeof ResetPasswordRoute
  '/signup': typeof SignupRoute
  '/auth/callback': typeof AuthCallbackRoute
  '/app/kitchen': typeof AuthenticatedAppKitchenRoute
  '/app/planner': typeof AuthenticatedAppPlannerRoute
  '/app/settings': typeof AuthenticatedAppSettingsRoute
  '/app': typeof AuthenticatedAppIndexRoute
  '/app/collections/$collectionId': typeof AuthenticatedAppCollectionsCollectionIdRoute
  '/app/recipes/import': typeof AuthenticatedAppRecipesImportRoute
  '/app/recipes/new': typeof AuthenticatedAppRecipesNewRoute
  '/app/shopping/$shoppingListId': typeof AuthenticatedAppShoppingShoppingListIdRoute
  '/app/collections': typeof AuthenticatedAppCollectionsIndexRoute
  '/app/recipes': typeof AuthenticatedAppRecipesIndexRoute
  '/app/shopping': typeof AuthenticatedAppShoppingIndexRoute
  '/app/recipes/$recipeId/edit': typeof AuthenticatedAppRecipesRecipeIdEditRoute
  '/app/recipes/$recipeId': typeof AuthenticatedAppRecipesRecipeIdIndexRoute
}
export interface FileRoutesById {
  __root__: typeof rootRouteImport
  '/': typeof IndexRoute
  '/_authenticated': typeof AuthenticatedRouteRouteWithChildren
  '/forgot-password': typeof ForgotPasswordRoute
  '/login': typeof LoginRoute
  '/reset-password': typeof ResetPasswordRoute
  '/signup': typeof SignupRoute
  '/auth/callback': typeof AuthCallbackRoute
  '/_authenticated/app/kitchen': typeof AuthenticatedAppKitchenRoute
  '/_authenticated/app/planner': typeof AuthenticatedAppPlannerRoute
  '/_authenticated/app/settings': typeof AuthenticatedAppSettingsRoute
  '/_authenticated/app/': typeof AuthenticatedAppIndexRoute
  '/_authenticated/app/collections/$collectionId': typeof AuthenticatedAppCollectionsCollectionIdRoute
  '/_authenticated/app/recipes/import': typeof AuthenticatedAppRecipesImportRoute
  '/_authenticated/app/recipes/new': typeof AuthenticatedAppRecipesNewRoute
  '/_authenticated/app/shopping/$shoppingListId': typeof AuthenticatedAppShoppingShoppingListIdRoute
  '/_authenticated/app/collections/': typeof AuthenticatedAppCollectionsIndexRoute
  '/_authenticated/app/recipes/': typeof AuthenticatedAppRecipesIndexRoute
  '/_authenticated/app/shopping/': typeof AuthenticatedAppShoppingIndexRoute
  '/_authenticated/app/recipes/$recipeId/edit': typeof AuthenticatedAppRecipesRecipeIdEditRoute
  '/_authenticated/app/recipes/$recipeId/': typeof AuthenticatedAppRecipesRecipeIdIndexRoute
}
export interface FileRouteTypes {
  fileRoutesByFullPath: FileRoutesByFullPath
  fullPaths:
    | '/'
    | '/forgot-password'
    | '/login'
    | '/reset-password'
    | '/signup'
    | '/auth/callback'
    | '/app/kitchen'
    | '/app/planner'
    | '/app/settings'
    | '/app/'
    | '/app/collections/$collectionId'
    | '/app/recipes/import'
    | '/app/recipes/new'
    | '/app/shopping/$shoppingListId'
    | '/app/collections/'
    | '/app/recipes/'
    | '/app/shopping/'
    | '/app/recipes/$recipeId/edit'
    | '/app/recipes/$recipeId/'
  fileRoutesByTo: FileRoutesByTo
  to:
    | '/'
    | '/forgot-password'
    | '/login'
    | '/reset-password'
    | '/signup'
    | '/auth/callback'
    | '/app/kitchen'
    | '/app/planner'
    | '/app/settings'
    | '/app'
    | '/app/collections/$collectionId'
    | '/app/recipes/import'
    | '/app/recipes/new'
    | '/app/shopping/$shoppingListId'
    | '/app/collections'
    | '/app/recipes'
    | '/app/shopping'
    | '/app/recipes/$recipeId/edit'
    | '/app/recipes/$recipeId'
  id:
    | '__root__'
    | '/'
    | '/_authenticated'
    | '/forgot-password'
    | '/login'
    | '/reset-password'
    | '/signup'
    | '/auth/callback'
    | '/_authenticated/app/kitchen'
    | '/_authenticated/app/planner'
    | '/_authenticated/app/settings'
    | '/_authenticated/app/'
    | '/_authenticated/app/collections/$collectionId'
    | '/_authenticated/app/recipes/import'
    | '/_authenticated/app/recipes/new'
    | '/_authenticated/app/shopping/$shoppingListId'
    | '/_authenticated/app/collections/'
    | '/_authenticated/app/recipes/'
    | '/_authenticated/app/shopping/'
    | '/_authenticated/app/recipes/$recipeId/edit'
    | '/_authenticated/app/recipes/$recipeId/'
  fileRoutesById: FileRoutesById
}
export interface RootRouteChildren {
  IndexRoute: typeof IndexRoute
  AuthenticatedRouteRoute: typeof AuthenticatedRouteRouteWithChildren
  ForgotPasswordRoute: typeof ForgotPasswordRoute
  LoginRoute: typeof LoginRoute
  ResetPasswordRoute: typeof ResetPasswordRoute
  SignupRoute: typeof SignupRoute
  AuthCallbackRoute: typeof AuthCallbackRoute
}

declare module '@tanstack/react-router' {
  interface FileRoutesByPath {
    '/': {
      id: '/'
      path: '/'
      fullPath: '/'
      preLoaderRoute: typeof IndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/_authenticated': {
      id: '/_authenticated'
      path: ''
      fullPath: '/'
      preLoaderRoute: typeof AuthenticatedRouteRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/forgot-password': {
      id: '/forgot-password'
      path: '/forgot-password'
      fullPath: '/forgot-password'
      preLoaderRoute: typeof ForgotPasswordRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/login': {
      id: '/login'
      path: '/login'
      fullPath: '/login'
      preLoaderRoute: typeof LoginRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/reset-password': {
      id: '/reset-password'
      path: '/reset-password'
      fullPath: '/reset-password'
      preLoaderRoute: typeof ResetPasswordRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/signup': {
      id: '/signup'
      path: '/signup'
      fullPath: '/signup'
      preLoaderRoute: typeof SignupRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/auth/callback': {
      id: '/auth/callback'
      path: '/auth/callback'
      fullPath: '/auth/callback'
      preLoaderRoute: typeof AuthCallbackRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/_authenticated/app/': {
      id: '/_authenticated/app/'
      path: '/app'
      fullPath: '/app/'
      preLoaderRoute: typeof AuthenticatedAppIndexRouteImport
      parentRoute: typeof AuthenticatedRouteRoute
    }
    '/_authenticated/app/kitchen': {
      id: '/_authenticated/app/kitchen'
      path: '/app/kitchen'
      fullPath: '/app/kitchen'
      preLoaderRoute: typeof AuthenticatedAppKitchenRouteImport
      parentRoute: typeof AuthenticatedRouteRoute
    }
    '/_authenticated/app/planner': {
      id: '/_authenticated/app/planner'
      path: '/app/planner'
      fullPath: '/app/planner'
      preLoaderRoute: typeof AuthenticatedAppPlannerRouteImport
      parentRoute: typeof AuthenticatedRouteRoute
    }
    '/_authenticated/app/settings': {
      id: '/_authenticated/app/settings'
      path: '/app/settings'
      fullPath: '/app/settings'
      preLoaderRoute: typeof AuthenticatedAppSettingsRouteImport
      parentRoute: typeof AuthenticatedRouteRoute
    }
    '/_authenticated/app/collections/': {
      id: '/_authenticated/app/collections/'
      path: '/app/collections'
      fullPath: '/app/collections/'
      preLoaderRoute: typeof AuthenticatedAppCollectionsIndexRouteImport
      parentRoute: typeof AuthenticatedRouteRoute
    }
    '/_authenticated/app/collections/$collectionId': {
      id: '/_authenticated/app/collections/$collectionId'
      path: '/app/collections/$collectionId'
      fullPath: '/app/collections/$collectionId'
      preLoaderRoute: typeof AuthenticatedAppCollectionsCollectionIdRouteImport
      parentRoute: typeof AuthenticatedRouteRoute
    }
    '/_authenticated/app/recipes/': {
      id: '/_authenticated/app/recipes/'
      path: '/app/recipes'
      fullPath: '/app/recipes/'
      preLoaderRoute: typeof AuthenticatedAppRecipesIndexRouteImport
      parentRoute: typeof AuthenticatedRouteRoute
    }
    '/_authenticated/app/recipes/import': {
      id: '/_authenticated/app/recipes/import'
      path: '/app/recipes/import'
      fullPath: '/app/recipes/import'
      preLoaderRoute: typeof AuthenticatedAppRecipesImportRouteImport
      parentRoute: typeof AuthenticatedRouteRoute
    }
    '/_authenticated/app/recipes/new': {
      id: '/_authenticated/app/recipes/new'
      path: '/app/recipes/new'
      fullPath: '/app/recipes/new'
      preLoaderRoute: typeof AuthenticatedAppRecipesNewRouteImport
      parentRoute: typeof AuthenticatedRouteRoute
    }
    '/_authenticated/app/shopping/': {
      id: '/_authenticated/app/shopping/'
      path: '/app/shopping'
      fullPath: '/app/shopping/'
      preLoaderRoute: typeof AuthenticatedAppShoppingIndexRouteImport
      parentRoute: typeof AuthenticatedRouteRoute
    }
    '/_authenticated/app/shopping/$shoppingListId': {
      id: '/_authenticated/app/shopping/$shoppingListId'
      path: '/app/shopping/$shoppingListId'
      fullPath: '/app/shopping/$shoppingListId'
      preLoaderRoute: typeof AuthenticatedAppShoppingShoppingListIdRouteImport
      parentRoute: typeof AuthenticatedRouteRoute
    }
    '/_authenticated/app/recipes/$recipeId/': {
      id: '/_authenticated/app/recipes/$recipeId/'
      path: '/app/recipes/$recipeId'
      fullPath: '/app/recipes/$recipeId/'
      preLoaderRoute: typeof AuthenticatedAppRecipesRecipeIdIndexRouteImport
      parentRoute: typeof AuthenticatedRouteRoute
    }
    '/_authenticated/app/recipes/$recipeId/edit': {
      id: '/_authenticated/app/recipes/$recipeId/edit'
      path: '/app/recipes/$recipeId/edit'
      fullPath: '/app/recipes/$recipeId/edit'
      preLoaderRoute: typeof AuthenticatedAppRecipesRecipeIdEditRouteImport
      parentRoute: typeof AuthenticatedRouteRoute
    }
  }
}

interface AuthenticatedRouteRouteChildren {
  AuthenticatedAppKitchenRoute: typeof AuthenticatedAppKitchenRoute
  AuthenticatedAppPlannerRoute: typeof AuthenticatedAppPlannerRoute
  AuthenticatedAppSettingsRoute: typeof AuthenticatedAppSettingsRoute
  AuthenticatedAppIndexRoute: typeof AuthenticatedAppIndexRoute
  AuthenticatedAppCollectionsCollectionIdRoute: typeof AuthenticatedAppCollectionsCollectionIdRoute
  AuthenticatedAppRecipesImportRoute: typeof AuthenticatedAppRecipesImportRoute
  AuthenticatedAppRecipesNewRoute: typeof AuthenticatedAppRecipesNewRoute
  AuthenticatedAppShoppingShoppingListIdRoute: typeof AuthenticatedAppShoppingShoppingListIdRoute
  AuthenticatedAppCollectionsIndexRoute: typeof AuthenticatedAppCollectionsIndexRoute
  AuthenticatedAppRecipesIndexRoute: typeof AuthenticatedAppRecipesIndexRoute
  AuthenticatedAppShoppingIndexRoute: typeof AuthenticatedAppShoppingIndexRoute
  AuthenticatedAppRecipesRecipeIdEditRoute: typeof AuthenticatedAppRecipesRecipeIdEditRoute
  AuthenticatedAppRecipesRecipeIdIndexRoute: typeof AuthenticatedAppRecipesRecipeIdIndexRoute
}

const AuthenticatedRouteRouteChildren: AuthenticatedRouteRouteChildren = {
  AuthenticatedAppKitchenRoute: AuthenticatedAppKitchenRoute,
  AuthenticatedAppPlannerRoute: AuthenticatedAppPlannerRoute,
  AuthenticatedAppSettingsRoute: AuthenticatedAppSettingsRoute,
  AuthenticatedAppIndexRoute: AuthenticatedAppIndexRoute,
  AuthenticatedAppCollectionsCollectionIdRoute:
    AuthenticatedAppCollectionsCollectionIdRoute,
  AuthenticatedAppRecipesImportRoute: AuthenticatedAppRecipesImportRoute,
  AuthenticatedAppRecipesNewRoute: AuthenticatedAppRecipesNewRoute,
  AuthenticatedAppShoppingShoppingListIdRoute:
    AuthenticatedAppShoppingShoppingListIdRoute,
  AuthenticatedAppCollectionsIndexRoute: AuthenticatedAppCollectionsIndexRoute,
  AuthenticatedAppRecipesIndexRoute: AuthenticatedAppRecipesIndexRoute,
  AuthenticatedAppShoppingIndexRoute: AuthenticatedAppShoppingIndexRoute,
  AuthenticatedAppRecipesRecipeIdEditRoute:
    AuthenticatedAppRecipesRecipeIdEditRoute,
  AuthenticatedAppRecipesRecipeIdIndexRoute:
    AuthenticatedAppRecipesRecipeIdIndexRoute,
}

const AuthenticatedRouteRouteWithChildren =
  AuthenticatedRouteRoute._addFileChildren(AuthenticatedRouteRouteChildren)

const rootRouteChildren: RootRouteChildren = {
  IndexRoute: IndexRoute,
  AuthenticatedRouteRoute: AuthenticatedRouteRouteWithChildren,
  ForgotPasswordRoute: ForgotPasswordRoute,
  LoginRoute: LoginRoute,
  ResetPasswordRoute: ResetPasswordRoute,
  SignupRoute: SignupRoute,
  AuthCallbackRoute: AuthCallbackRoute,
}
export const routeTree = rootRouteImport
  ._addFileChildren(rootRouteChildren)
  ._addFileTypes<FileRouteTypes>()

import type { getRouter } from './router.tsx'
import type { startInstance } from './start.ts'
declare module '@tanstack/react-start' {
  interface Register {
    ssr: true
    router: Awaited<ReturnType<typeof getRouter>>
    config: Awaited<ReturnType<typeof startInstance.getOptions>>
  }
}
